const kAssets = 'assets/images';

enum AppImages {
  logoGif("$kAssets/logo_gif.gif"),
  webHeader("$kAssets/web_header.png"),
  splashLogo("$kAssets/splash_logo.png"),
  splashLogo2("$kAssets/splash_logo2.png"),
  authBackground("$kAssets/auth_background_new.jpg"),
  rightArrow("$kAssets/right-arrow.png"),
  rightArrowGreen("$kAssets/right_arrow_green.png"),
  backgroundImage("$kAssets/backgroundImage.png"),
  buttonIcon("$kAssets/buttonIcon.png"),
  arrowBack("$kAssets/arrow-back.png"),
  loadingGif("$kAssets/loading.gif"),
  dialogBg("$kAssets/dialog_bg.png"),
  selectedTag("$kAssets/selected_tag.png"),
  unselectedTag("$kAssets/un_selected_tag.png"),
  noNotificationBell("$kAssets/no_notification_bell.png"),
  notificationBell("$kAssets/notification_bell.png"),
  logo("$kAssets/logo.png"),
  calendar("$kAssets/calendar.png"),
  tennisBall("$kAssets/tennis-ball.png"),
  iconCamera("$kAssets/icon_camera.png"),
  iconCameraNew("$kAssets/icon_camera_new.png"),
  crossIcon("$kAssets/cross-icon.png"),
  backArrow("$kAssets/back-arrow.png"),
  whatsaapIcon("$kAssets/whatsaap-icon.png"),
  shareIcon("$kAssets/share_icon.png"),
  levelAssessment("$kAssets/level_assessment.png"),

  editIcon("$kAssets/edit_icon.png"),
  dropdownIcon("$kAssets/dropdown_icon.png"),
  creditCardIcon("$kAssets/credit_card_icon.png"),
  creditCard2("$kAssets/credit_card_2.png"),
  walletIcon("$kAssets/wallet-icon.png"),
  filterIcon("$kAssets/filter-icon.png"),
  infoIcon("$kAssets/info_icon.png"),
  // logoWebHeader("$kAssets/logo_web_header.png"),
  closeIcon("$kAssets/close_icon.png"),
  checkIcon("$kAssets/check_icon.png"),
  checkMark("$kAssets/check_mark.png"),
  applePay("$kAssets/apple_pay.png"),
  apple("$kAssets/apple.png"),
  chatIconRead("$kAssets/chat_icon_read.png"),
  chatIconUnRead("$kAssets/chat_icon_un_read.png"),
  google("$kAssets/google.png"),
  warning("$kAssets/warning.png"),
  warning2("$kAssets/warning_2.png"),
  refresh("$kAssets/refresh.png"),
  back_arrow_new("$kAssets/back_arrow_new.png"),
  send_us("$kAssets/send_us.png"),
  membershipCard("$kAssets/membership_card.png"),
  membershipGoldCard("$kAssets/membership_gold_card.png"),
  hopSmall("$kAssets/hop_small.png"),
  trophy("$kAssets/trophy.png"),
  addUser("$kAssets/add_user.png"),
  ;

  final String path;
  const AppImages(this.path);
}
