// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        return android;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ScEHoPjdIY5yTlsu8jlKKXoDyf0Pn1E',
    appId: '1:264818472122:android:c094929e0ab76ceef93e83',
    messagingSenderId: '264818472122',
    projectId: 'padel-art-2',
    storageBucket: 'padel-art-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS0n2JoA6IMnACnrZyAseRi9MWWe83Xpo',
    appId: '1:264818472122:ios:aa15422ee5b8a0c7f93e83',
    messagingSenderId: '264818472122',
    projectId: 'padel-art-2',
    storageBucket: 'padel-art-2.appspot.com',
    iosBundleId: 'com.padelrush.bookandgo',
  );
}
