// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return web;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-PmQOZM8YFV61R8eWzGg3vNGWrIV82Ew',
    appId: '1:808637490319:web:3d93741f0fdcd17c7cbcfa',
    messagingSenderId: '808637490319',
    projectId: 'frontendbooakdngo3',
    authDomain: 'frontendbooakdngo3.firebaseapp.com',
    storageBucket: 'frontendbooakdngo3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZSHzjzdh1A8J_Ini5CEA0GIwJh0MOmjQ',
    appId: '1:808637490319:android:4f9a7e1ba5716aad7cbcfa',
    messagingSenderId: '808637490319',
    projectId: 'frontendbooakdngo3',
    storageBucket: 'frontendbooakdngo3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCJDvBaX9K0LOMpcHri0miwk5Q5rZ4tCY',
    appId: '1:808637490319:ios:51f944749bbe9a3c7cbcfa',
    messagingSenderId: '808637490319',
    projectId: 'frontendbooakdngo3',
    storageBucket: 'frontendbooakdngo3.firebasestorage.app',
    iosBundleId: 'com.padelrush.bookandgo',
  );

}